"""
Django settings for Help_dasks project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import logging.config
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#DATABASE_DIR = BASE_DIR / "database"
#DATABASE_DIR.mkdir(exist_ok=True)


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'#config('DEFAULT_FILE_STORAGE')
AWS_ACCESS_KEY_ID = 'minioadmin'#config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = 'minioadmin'#config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'telegram'#config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = 'http://minio:9000'
AWS_S3_FILE_OVERWRITE = False
AWS_LOCATION = 'static'

RABBIT_HOST = 'localhost'#config('RABBIT_HOST')
RABBIT_QUEUE = 'hello'#config('RABBIT_QUEUE')
RABBIT_QUEUE_SEND = 'hello'#config('RABBIT_QUEUE_SEND')
RABBIT_ROUTING_KEY = 'hello'#config('RABBIT_ROUTING_KEY')

BOT_TOKEN = '6880396170:AAEi9ZWvprUuHSXy1qTFzPG0mx5Sy9Md5Dw'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8r+5(vc7yu@k5a_p4k(!xwex%#0+9xxh!u8+zp+z88+mgrlb!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True#getenv('DJANGO_DEBUG', '0') == "1"

ALLOWED_HOSTS = [
    "*",
    "127.0.0.1",
    "0.0.0.0"
] + config("DJANGO_ALLOWED_HOSTS", "").split(",")


AUTH_USER_MODEL = 'profile.User'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "profile",
    "users",
    "application",
    "storages",
    "django.contrib.postgres",
    "static",
    'rest_framework',
    'corsheaders',
    #'rest_framework_simplejwt',
]

MIDDLEWARE = [
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_currentuser.middleware.ThreadLocalUserMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "Help_dasks.urls"

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]

CORS_TRUSTED_ORIGINS = ["http://localhost:3000"]

CORS_ALLOW_HEADERS = (
    'Access-Control-Allow-Headers',
    'Access-Control-Allow-Credentials',
)

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8000',
]

#REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#        'rest_framework_simplejwt.authentication.JWTAuthentication',
#    ),
#    'DEFAULT_PERMISSION_CLASSES': [],
#
#}


REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': [
       'rest_framework_simplejwt.authentication.JWTAuthentication',
   ]
}

SIMPLE_JWT = {
   'ACCESS_TOKEN_LIFETIME': timedelta(hours=10),
   'REFRESH_TOKEN_LIFETIME': timedelta(hours=10),
   'ROTATE_REFRESH_TOKENS': True,
   'BLACKLIST_AFTER_ROTATION': True,
   'UPDATE_LAST_LOGIN': False,
   'ALGORITHM': 'HS256',
   'VERIFYING_KEY': None,
   'AUDIENCE': None,
   'ISSUER': None,
   'JWK_URL': None,
   'LEEWAY': 0,
   'AUTH_HEADER_TYPES': ('Bearer',),
   'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
   'USER_ID_FIELD': 'id',
   'USER_ID_CLAIM': 'user_id',
   'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
   'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
   'TOKEN_TYPE_CLAIM': 'token_type',
   'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
   'JTI_CLAIM': 'jti',
   'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
   'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
   'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = "Help_dasks.wsgi.application"

LOGIN_REDIRECT_URL = '/../app/aplications-list'
LOGOUT_REDIRECT_URL = "login"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': 'helpDesk',
       'USER': 'postgres',
       'PASSWORD': 'root',
       'HOST': "127.0.0.1",
       'PORT': '5432',
   }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

#STATICFILES_DIRS = [
#   os.path.join(Path(__file__).resolve().parent.parent, "static"),
#]

STATIC_ROOT=os.path.join(BASE_DIR, "/static/")

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

#DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

