# Generated by Django 3.2.16 on 2023-12-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.CharField(default='Web-request', max_length=50)),
                ('team', models.CharField(default='', max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('messages_id', models.CharField(default='', max_length=50)),
                ('priority', models.CharField(default='', max_length=50)),
                ('chat_id', models.CharField(max_length=50, null=True)),
                ('telegram', models.BooleanField(default=False, null=True)),
                ('mail', models.BooleanField(default=False, null=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegram/')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegram/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('messages_id', models.TextField(default='', max_length=50, null=True)),
                ('telegram', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.CharField(max_length=50, null=True)),
                ('mail', models.BooleanField(default=False, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.application')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
